export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
export const CLEAR_STATE_CITIES = 'CLEAR_STATE_CITIES';
export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
